# Make some basic iControlRest calls to setup network elements on BIG-IP
# A more polished implementation might include custom ansible modules for these
# steps. 

# Instead we use iControlRest (nearly) directly.  We wrap the iCR calls to 
# provide a bit of idempotence.  See library/bigip_config
---

# ----------------------------------------------------------------------
# License BIGIP 
# ----------------------------------------------------------------------


# Example of setting license for license.f5.com in 12.0.0+ w/ REST
# Assuming BIG-IPs have access to license server
# - name: License BIG-IP for BYOL
#   delegate_to: localhost
#   bigip_config:
#     state=present
#     host={{ inventory_hostname }}
#     user={{ bigip_rest_user }}
#     password={{ bigip_rest_pass }}
#     payload='{"command":"install", "registrationKey":"{{RegKey}}","licenseServer":"{{license_server}}"}'
#     collection_path='mgmt/tm/sys/license'
#

# - name: License the bigip using old script
#   script: ../library/bigip_license_bigsuds.py -b {{ansible_ssh_host}} -u \'{{bigip_rest_user}}\' -p \'{{bigip_rest_password}}\' -r \'{{RegKey}}\' -s {{license_server}}
#   delegate_to: localhost

- name: License the bigip using Ansible Module
  bigip_license: 
     server={{ ansible_ssh_host }}
     username={{ bigip_rest_user }}
     password={{ bigip_rest_password }}
     key={{ RegKey }}
     validate_certs=False
  delegate_to: localhost



