---
# tasks file for app role
# ensures the set of containers are running
- docker:
      image: "{{ image_id }}"
      count: 1
      ports: 80:80
      # count: "{{ container_cnt }}"
      # publish_all_ports: true
      state: running
  tags: 
     - launch_containers
  register: launched_containers
  until: launched_containers["failed"] == false
  retries: 5
  delay: 10
