- name: Provisioning module
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ ansible_ssh_host }}
    user={{ bigip_rest_user }}
    password={{ bigip_rest_password }}
    payload='{"level":"nominal"}'
    collection_path='mgmt/tm/sys/provision/{{module}}'

- name: Wait for module completion to avoid any race conditions
  pause: seconds=30