
############## BEGIN COLLECTING/SETTING VARIABLES ######

- hosts: bigip-01
  connection: local
  gather_facts: False
  tasks:

    - name: Load customer_gateway_configuration from XML
      set_fact:
          customer_gateway_config: "{{ lookup('file', '../cache/' + env_tag + '/vpn_conn_01_customer_gateway_configuration.xml') | xml_to_dict }}"
          connection: "conn_1"

- hosts: bigip-02
  connection: local
  gather_facts: False
  tasks:

    - name: Load customer_gateway_configuration from XML
      set_fact:
          customer_gateway_config: "{{ lookup('file', '../cache/' + env_tag + '/vpn_conn_02_customer_gateway_configuration.xml') | xml_to_dict }}"
          connection: "conn_2"

- hosts: bigips
  connection: local
  gather_facts: False
  vars_files:
      - "~/creds.yml"
  pre_tasks:

    # - name: debug hosts before set fact
    #   debug: var=hostvars[inventory_hostname]

      ##### IMPORT/CONVERT DATA FROM DIFFERNT SOURCES TO FIT ROLES #####
      # ex. massage the variables from static configs to better fit 
      # roles from github/f5networks/aws-deployments
    - name: 
      set_fact: 
        ansible_ssh_host={{ hostvars[inventory_hostname].SETTINGS.bigip }}
        ansible_ssh_user={{ ansible_ssh_user }}
        bigip_rest_user={{ bigip_rest_user }}
        bigip_rest_password={{ bigip_rest_password }}
        install_path={{install_path}}
        DeviceName={{ hostvars[inventory_hostname].SETTINGS.hostname }}
        ManagementInterfacePrivateIp={{ hostvars[inventory_hostname].SETTINGS.bigip }}
        ManagementInterfacePublicIp={{ hostvars[inventory_hostname].SETTINGS.bigip }}
        ExternalInterfacePublicIp="Not Used"
        RegKey="{{hostvars[inventory_hostname].SETTINGS.reg_keys_string}}"
        license_server="{{hostvars[inventory_hostname].SETTINGS.license_server_hostname}}"
        modules="{{hostvars[inventory_hostname].SYSTEM.PROVISIONING.keys() }}"
        db_keys="{{hostvars[inventory_hostname].SYSTEM.DB_KEYS}}"
        ntp_server="{{hostvars[inventory_hostname].SYSTEM.NTP.ntp_servers[0]}}"
        timezone="{{hostvars[inventory_hostname].SYSTEM.NTP.timezone}}"
        dns_server="{{hostvars[inventory_hostname].SYSTEM.DNS.dns_servers[0]}}"
        vlans="{{hostvars[inventory_hostname].NETWORK.VLANS}}"
        self_ips="{{hostvars[inventory_hostname].NETWORK.SELF_IPS}}"
        routes="{{hostvars[inventory_hostname].NETWORK.ROUTES}}"

    # Had to filter a bit more for varables below as there may be multiple Self-IPs that could match
    - name: set ExternalInterfacePrivateIp
      set_fact: 
        ExternalInterfacePrivateIp={{ item.address }}
      with_items: hostvars[inventory_hostname].NETWORK.SELF_IPS 
      when: item.tag is defined and item.tag == "ExternalInterfacePrivateIp"

    - name: set InternalInterfacePrivateIp
      set_fact: 
        InternalInterfacePrivateIp={{ item.address }}
        InternalNetwork={{ item.address | ipsubnet(item.cidr) }}
      with_items: hostvars[inventory_hostname].NETWORK.SELF_IPS 
      when: item.tag is defined and item.tag == "InternalInterfacePrivateIp"

    # - name: debug hosts after set fact
    #   debug: var=hostvars[inventory_hostname]

############## END COLLECTING/SETTING VARIABLES ######





############## BEGIN CONFIGURE BASE CONFIGS ##########

# SSH to each device using ssh key, add a REST user and change the GUI admin password
- hosts: bigips
  gather_facts: False
  roles:
    # adds users via tmsh
    - bigip_base
    # starting with 11.6, AWS defaults to admin & tmsh as shell so need different role
    # - bigip_base_aws

# Connection = local as rest calls from the automation host
- hosts: bigips
  connection: local
  gather_facts: False
  roles:
    # # licenses bigip
    - bigip_license
    # # provisions system globals like ntp, dns, snmp, syslog, db keys
    - bigip_system
    # sets vlans, self-ips, routes
    - bigip_network

############## END CONFIGURE BASE CONFIGS ############





############## BEGIN CLUSTER THE DEVICES #############

- hosts: bigip-cluster-names
  gather_facts: no
  connection: local
  tasks:
    - name: create a dynamic group of seed devices using first member of each group
      add_host:
          name: "{{ item.value.0 }}"
          group: bigip-cluster-seeds
          cluster_name: "{{ item.key }}"
          members: "{{ item.value }}"
      with_dict: groups
      when: item.key in groups['bigip-cluster-names']

    - name: debug groups
      debug: var=groups

- hosts: bigip-cluster-seeds
  gather_facts: no
  connection: local
  tasks:

      #- name: debug hosts
      #  debug: var=hostvars[inventory_hostname]

      # Difficult to selectively grab/loop through variables and construct string together
      # in play framework itself. Easiest way is through a template.

      - name: Store peers information
        template: src=../roles/bigip_cluster/templates/cluster_peer_info.cfg.j2 dest=../cache/{{ env_tag }}/{{inventory_hostname}}_peer_info.yml
        delegate_to: localhost

# # Add peer variables to host from template output above
- hosts: bigip-cluster-seeds
  gather_facts: no
  vars_files:
    - [ "../cache/{{ env_tag }}/{{inventory_hostname}}_peer_info.yml" ]
  roles:
     # This role configures the device object on each bigip and clusters them
     - bigip_cluster

######## END CLUSTER DEVICES ############





######## BEGIN VPN SPECIFIC CONFIG ##########

- hosts: bigip-01
  gather_facts: no
  roles:
    - bigip_vpn
   
- hosts: bigip-02
  gather_facts: no
  pre_tasks:
    - name: pause to allow time to sync shared vpn config elements
      pause: seconds=20
  roles:
    - bigip_vpn

######## END VPN SPECIFIC CONFIG ##########





######## BEGIN MISC SHARED CONFIG ##########

##### As Tunnels will only activate on an Active device, 
##### We will add a couple more traffic groups in order to keep each device Active

- hosts: bigip-cluster-seeds
  gather_facts: no
  tasks:

    - name: Adding Traffic Group 2 To Keep BIG-IP-1 ACTIVE
      delegate_to: localhost
      bigip_config:
        state=present
        host={{ ansible_ssh_host }}
        user={{ bigip_rest_user }}
        password={{ bigip_rest_password }}
        collection_path='mgmt/tm/cm/traffic-group'
        resource_key="name"
        payload='{
                  "name":"traffic-group-2",
                  "autoFailbackEnabled":"true",
                  "haOrder":[
                        "{{hostvars['bigip-01'].DeviceName}}",
                        "{{hostvars['bigip-02'].DeviceName}}"
                  ]
                  }'


    - name: Adding Traffic Group 3 To Keep BIG-IP-2 ACTIVE
      delegate_to: localhost
      bigip_config:
        state=present
        host={{ ansible_ssh_host }}
        user={{ bigip_rest_user }}
        password={{ bigip_rest_password }}
        collection_path='mgmt/tm/cm/traffic-group'
        resource_key="name"
        payload='{
                  "name":"traffic-group-3",
                  "autoFailbackEnabled":"true",
                  "haOrder":[
                        "{{hostvars['bigip-02'].DeviceName}}",
                        "{{hostvars['bigip-01'].DeviceName}}"
                  ]
                  }'

    # OPTIONAL OUTBOUND VIRTUAL FOR TESTING CLIENTS BEHIND BIG-IPs
    - name: Adding Forwarding Virtual
      delegate_to: localhost
      bigip_config:
        state=present
        host={{ ansible_ssh_host }}
        user={{ bigip_rest_user }}
        password={{ bigip_rest_password }}
        collection_path='mgmt/tm/ltm/virtual'
        resource_key="name"
        payload='{
                  "name":"vs_outbound",
                  "destination":"/Common/0.0.0.0:0",
                  "mask":"any",
                  "ipProtocol":"any",
                  "translateAddress":"disabled",
                  "translatePort":"disabled",
                  "sourceAddressTranslation":{"type":"none"},
                  "profiles":[{"name":"fastL4-route-friendly","context":"all"}],
                  "ipForward":true
                  }'

######## END MISC SHARED CONFIG ##########



