---
# ---------------------------------
# Configure network, LTM, and ASM settings which are specific to each device.
# ---------------------------------

# - name: Adding/updating internal vlan
#   delegate_to: localhost
#   bigip_config:
#     state=present
#     host={{ ansible_ssh_host }}
#     user={{ bigip_rest_user }}
#     password={{ bigip_rest_password }}
#     payload='{"name":"private", "interfaces":"1.2"}'
#     collection_path='mgmt/tm/net/vlan'
#     resource_key="name"

- name: Adding/updating vlans
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ ansible_ssh_host }}
    user={{ bigip_rest_user }}
    password={{ bigip_rest_password }}
    payload='{"name":"{{item.key}}", "interfaces":"{{item.value.interfaces}}" }'
    collection_path='mgmt/tm/net/vlan'
    resource_key="name"
  with_dict: vlans


- name: Adding/updating self-ips
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ ansible_ssh_host }}
    user={{ bigip_rest_user }}
    password={{ bigip_rest_password }}
    payload='{"name":"{{item.name}}", "address":"{{item.address}}/{{item.cidr}}", "vlan":"{{item.vlan}}", "trafficGroup":"{{item.traffic_group}}", "allowService":["{{item.allow_service}}"]}'
    collection_path='mgmt/tm/net/self'
    resource_key="name"
  with_items: self_ips


# Gateway pools only needed in Cluster spanned across AZs and will be shared on all devices
# Commenting out now but will just need to add separate more specific roles or conditions inside the roles 
# - name: Adding/updating default gateway pool
#   delegate_to: localhost
#   bigip_config:
#     state=present
#     host={{ ansible_ssh_host }}
#     user={{ bigip_rest_user }}
#     password={{ bigip_rest_password }}
#     payload='{"name":"default_gateway_pool", "members":[{"name":"172.16.2.1:0","address":"172.16.2.1"}, {"name":"172.16.12.1:0","address":"172.16.12.1"}], "monitor":"gateway_icmp"}'
#     collection_path='mgmt/tm/ltm/pool'
#     resource_key="name"

# - name: Adding/updating pool members for default gateway pool
#   delegate_to: localhost
#   bigip_config:
#     state=present
#     host={{ ansible_ssh_host }}
#     user={{ bigip_rest_user }}
#     password={{ bigip_rest_password }}
#     payload='{ "name":"pool_member_gateway_pool", "members":[{"name":"172.16.3.1:0","address":"172.16.3.1"}, {"name":"172.16.13.1:0","address":"172.16.13.1"}], "monitor":"gateway_icmp" }'
#     collection_path='mgmt/tm/ltm/pool'
#     resource_key="name"


#  for each bigip the routes may be different
#  In Amazon, the Default Gateway is 
#  the first IP on the subnet network, i.e. 172.16.12.1 and 172.16.22.1
#  So we'll hardcode and just replace the '0' with a '1' from the variable 'public_cidr'. 
#  This might not be true in other environments, in which case we'll want a more robust solution.
# - name: Setting default route using default_gateway or gateway_pool
#   delegate_to: localhost
#   bigip_config:
#     state=present
#     host={{ ansible_ssh_host }}
#     user={{ bigip_rest_user }}
#     password={{ bigip_rest_password }}
#     payload='{"name":"default_route", "network":"default", "gw":"{{ [ExternalInterfacePrivateIp[0:9],1]|join('.') }}" }'
#     collection_path='/mgmt/tm/net/route'
#     resource_key="name"

# BZID 510170 - Must include partition 
- name: Setting default route using default_gateway or gateway_pool
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ ansible_ssh_host }}
    user={{ bigip_rest_user }}
    password={{ bigip_rest_password }}
    payload='{
              "name":"{{item.key}}",
              "partition":"Common",
              "network":"{{item.value.network}}/{{ item.value.cidr }}",
              "gw":"{{ item.value.gw }}" 
            }'
    collection_path='/mgmt/tm/net/route'
    resource_key="name"
  with_dict: routes



